/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab4swing_3b_españo;

import javax.swing.JOptionPane;

/**
 *
 * @author STUDENT
 */
public class MilkteaFrame extends javax.swing.JFrame {
    
    private double priceSize, subtotalPrice,totalPrice, QTYprice, discountAmount;

    /**
     * Creates new form MilkteaFrame
     */
    public MilkteaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_flavor = new javax.swing.JComboBox<>();
        cmb_size = new javax.swing.JComboBox<>();
        chk_pearl = new javax.swing.JCheckBox();
        chk_pudding = new javax.swing.JCheckBox();
        chk_crystal = new javax.swing.JCheckBox();
        chk_creamcheese = new javax.swing.JCheckBox();
        txt_QTY = new javax.swing.JTextField();
        btn_compute = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chk_discount = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        btn_change = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_discount = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_change = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_totalsales = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_clearsales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Milktea Frame");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("KAISUNOO'S MILKTEAHAN");
        jLabel1.setMaximumSize(new java.awt.Dimension(136, 24));
        jLabel1.setMinimumSize(new java.awt.Dimension(136, 24));
        jLabel1.setPreferredSize(new java.awt.Dimension(136, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Flavor:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Size:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Add-ons");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Quantity:");

        cmb_flavor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmb_flavor.setForeground(new java.awt.Color(51, 51, 51));
        cmb_flavor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Okinawa", "Taro Milk tea", "Thai Milk tea" }));

        cmb_size.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmb_size.setForeground(new java.awt.Color(51, 51, 51));
        cmb_size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tall", "Grande", "Venti" }));

        chk_pearl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_pearl.setForeground(new java.awt.Color(51, 51, 51));
        chk_pearl.setText("Pearl");
        chk_pearl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_pearlActionPerformed(evt);
            }
        });

        chk_pudding.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_pudding.setForeground(new java.awt.Color(51, 51, 51));
        chk_pudding.setText("Pudding");

        chk_crystal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_crystal.setForeground(new java.awt.Color(51, 51, 51));
        chk_crystal.setText("Crystal");

        chk_creamcheese.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chk_creamcheese.setForeground(new java.awt.Color(51, 51, 51));
        chk_creamcheese.setText("Cream Cheese");

        txt_QTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QTYActionPerformed(evt);
            }
        });

        btn_compute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_compute.setForeground(new java.awt.Color(51, 51, 51));
        btn_compute.setText("Compute");
        btn_compute.setActionCommand("");
        btn_compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_computeActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("==================================================");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Subtotal:");

        lbl_subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_subtotal.setForeground(new java.awt.Color(255, 51, 51));
        lbl_subtotal.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Discount:");

        chk_discount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chk_discount.setForeground(new java.awt.Color(51, 51, 51));
        chk_discount.setText("PWD/Senior (20%)");
        chk_discount.setActionCommand("");
        chk_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_discountActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Cash:");

        btn_change.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_change.setForeground(new java.awt.Color(51, 51, 51));
        btn_change.setText("Compute Change");
        btn_change.setActionCommand("");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("==================================================");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Discount Amount:");

        lbl_discount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_discount.setForeground(new java.awt.Color(255, 51, 51));
        lbl_discount.setText("0.00");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Total:");

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(255, 51, 51));
        lbl_total.setText("0.00");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Change:");

        lbl_change.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_change.setForeground(new java.awt.Color(255, 51, 51));
        lbl_change.setText("0.00");

        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(51, 51, 51));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(51, 51, 51));
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_save.setForeground(new java.awt.Color(51, 51, 51));
        btn_save.setText("Save Transaction");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("==================================================");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Hello:  Customer!");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Total Sales:");

        lbl_totalsales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_totalsales.setForeground(new java.awt.Color(51, 51, 51));
        lbl_totalsales.setText("0.00");

        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("==================================================");

        btn_clearsales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_clearsales.setForeground(new java.awt.Color(51, 51, 51));
        btn_clearsales.setText("Clear Sales");
        btn_clearsales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearsalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_totalsales)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_size, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_flavor, 0, 173, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_pearl)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(chk_pudding)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk_creamcheese)
                            .addComponent(chk_crystal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_compute, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_QTY, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chk_discount)
                            .addComponent(lbl_subtotal)
                            .addComponent(txt_cash)
                            .addComponent(btn_change, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_total)
                            .addComponent(lbl_discount)
                            .addComponent(lbl_change)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_clearsales, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_logout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_flavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_pearl)
                    .addComponent(chk_crystal)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_pudding)
                    .addComponent(chk_creamcheese))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_QTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_compute)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(chk_discount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_change)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_discount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lbl_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbl_change))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_logout)
                    .addComponent(btn_cancel)
                    .addComponent(btn_save))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(lbl_totalsales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clearsales)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chk_pearlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_pearlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_pearlActionPerformed

    private void txt_QTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QTYActionPerformed

    private void chk_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_discountActionPerformed

    private void btn_computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_computeActionPerformed
        QTYprice = Double.parseDouble(txt_QTY.getText()); //parsing the string from jTextField into double
        
        if(cmb_size.getSelectedItem().equals("Tall")){
            priceSize = 120;
            getTotal();
        }else if(cmb_size.getSelectedItem().equals("Grande")){
            priceSize = 180;
            getTotal();
        }else if(cmb_size.getSelectedItem().equals("Venti")){
            priceSize = 200;
            getTotal();
        }
    }
    
    private void getTotal(){
        if(chk_pearl.isSelected() && chk_pudding.isSelected() && chk_crystal.isSelected() && chk_creamcheese.isSelected()){
            subtotalPrice = (priceSize + 15 + 20 + 10 + 25)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_pearl.isSelected() && chk_pudding.isSelected() && chk_crystal.isSelected()){
            subtotalPrice = (priceSize + 15 + 20 + 10)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_pearl.isSelected() && chk_pudding.isSelected() && chk_creamcheese.isSelected()){
            subtotalPrice = (priceSize + 15 + 20 + 25)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_pearl.isSelected() && chk_crystal.isSelected() && chk_creamcheese.isSelected()){
            subtotalPrice = (priceSize + 15 + 10 + 25)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_pudding.isSelected() && chk_crystal.isSelected() && chk_creamcheese.isSelected()){
            subtotalPrice = (priceSize + 20 + 10 + 25)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_pearl.isSelected()){
            subtotalPrice = (priceSize + 15)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_pudding.isSelected()){
            subtotalPrice = (priceSize + 20)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_crystal.isSelected()){
            subtotalPrice = (priceSize + 10)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else if(chk_creamcheese.isSelected()){
            subtotalPrice = (priceSize + 25)*QTYprice;
            lbl_subtotal.setText(Double.toString(subtotalPrice));
        }else { }
    }//GEN-LAST:event_btn_computeActionPerformed

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        double changeTotal;
        
        if(chk_discount.isSelected()){
            discountAmount = subtotalPrice*0.2;
            lbl_discount.setText(Double.toString(discountAmount));
            totalPrice = subtotalPrice - discountAmount;
            lbl_total.setText(Double.toString(totalPrice));
            changeTotal = Double.parseDouble(txt_cash.getText()) - Double.parseDouble(lbl_total.getText());
            lbl_change.setText(Double.toString(changeTotal));
        }else {
            changeTotal = Double.parseDouble(txt_cash.getText()) - Double.parseDouble(lbl_total.getText());
            lbl_change.setText(Double.toString(changeTotal)); 
        }
    }//GEN-LAST:event_btn_changeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String previousTotalText = lbl_totalsales.getText();
        
        if (!previousTotalText.isEmpty()) {
            double previousTotal = Double.parseDouble(previousTotalText);
            totalPrice += previousTotal;
        }
        
        int saveAnswer;
        
        saveAnswer = JOptionPane.showConfirmDialog(null, "Save Transaction?"); //import>2 parameter
        
        if(saveAnswer==JOptionPane.YES_OPTION){
            lbl_totalsales.setText(Double.toString(totalPrice));
            JOptionPane.showMessageDialog(this, "Transaction saved!");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int logoutAnswer;
        
        logoutAnswer = JOptionPane.showConfirmDialog(null, "Logout?"); //import>2 parameter
        if(logoutAnswer==JOptionPane.YES_OPTION){
            LoginFrame TF = new LoginFrame();
            TF.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        int cancelAnswer;
        
        cancelAnswer = JOptionPane.showConfirmDialog(null, "Cancel Transaction?"); //import>2 parameter
        if(cancelAnswer==JOptionPane.YES_OPTION){
            lbl_subtotal.setText("0.00");
            lbl_discount.setText("0.00");
            lbl_total.setText("0.00");
            lbl_change.setText("0.00");
            txt_QTY.setText("");
            txt_cash.setText("");
            chk_pearl.setSelected(false);
            chk_pudding.setSelected(false);
            chk_crystal.setSelected(false);
            chk_creamcheese.setSelected(false);
        }
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_clearsalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearsalesActionPerformed
        int clearSales;
        
        clearSales = JOptionPane.showConfirmDialog(null, "Clear sales?"); //import>2 parameter
        if(clearSales==JOptionPane.YES_OPTION){
            lbl_totalsales.setText("0.00");
        }
    }//GEN-LAST:event_btn_clearsalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MilkteaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MilkteaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MilkteaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MilkteaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MilkteaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_change;
    private javax.swing.JButton btn_clearsales;
    private javax.swing.JButton btn_compute;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_save;
    private javax.swing.JCheckBox chk_creamcheese;
    private javax.swing.JCheckBox chk_crystal;
    private javax.swing.JCheckBox chk_discount;
    private javax.swing.JCheckBox chk_pearl;
    private javax.swing.JCheckBox chk_pudding;
    private javax.swing.JComboBox<String> cmb_flavor;
    private javax.swing.JComboBox<String> cmb_size;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_change;
    private javax.swing.JLabel lbl_discount;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_totalsales;
    private javax.swing.JTextField txt_QTY;
    private javax.swing.JTextField txt_cash;
    // End of variables declaration//GEN-END:variables
}
